### ISSUE TITLE
Setup slides for presentation

### ISSUE THREAD

**Issue by lrobert142** [CP3402-2017-1/a2-cp3402-2017-team24#109]
Slides should detail our workflow:
  * How we approached the problem
  * How we delegated tasks
  * The tools we used and why we used them
  * Any obstacles we encountered
  * ???

**Comment by Sedgy** [comment]
https://docs.google.com/presentation/d/1Sx_3HyL7IVCvNeK04RWtpUW2D4-tFtXAVWMvTZhPWUY/edit?usp=sharing
