### ISSUE TITLE
Investigate WordPress Pipeline Options

### ISSUE THREAD

**Issue by axrs** [CP3402-2017-1/a2-cp3402-2017-team24#5]
We need to integrate a deployment pipeline. The pipeline must allow for `Localhost --> Staging --> Production` style deployments.

Things to consider are also Database Procedures.

**Comment by axrs** [comment]
Rock an AWS infrastructure:
- @lrobert142 Production
- @Sedgy Staging

**Comment by axrs** [comment]
Still to investigate MySQL Versioning
* May need custom bash to clone/restore

**Comment by lrobert142** [comment]
Duplicate of #28
